// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'carousel': string;
  'carouselFrame': string;
  'root': string;
  'video': string;
}
declare var cssExports: CssExports;
export = cssExports;
