// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'destructive': string;
  'primary': string;
  'root': string;
  'secondary': string;
}
declare var cssExports: CssExports;
export = cssExports;
