// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'dot': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
