// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'h1': string;
  'h2': string;
  'paragraph': string;
}
declare var cssExports: CssExports;
export = cssExports;
