// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'chevronDown': string;
  'divider': string;
  'line': string;
  'list': string;
  'listActive': string;
  'listItem': string;
  'listItemInitial': string;
  'listItemSelected': string;
  'root': string;
  'select': string;
}
declare var cssExports: CssExports;
export = cssExports;
