// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'input': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
