// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'container': string;
  'label': string;
  'root': string;
  'slider': string;
}
declare var cssExports: CssExports;
export = cssExports;
